### ISSUE TITLE
Labelling of Axes

### ISSUE THREAD

**Issue by MayaStr** [giangtle/DRT_Lib#1]
Hi Giangtle,

thank you for sharing your code! I am quite happy I can use it for my imedance spectra. :)

When excecuting the DRT with display=True, the created plot of DRT has the axis labels of a Nyquist plot. I guess the x-axis should be a frequency and the y-axis should be something like DRT.

**Comment by giangtle** [comment]
Hi MayaStr, 
You're right! Thanks for catching this.
